# Device configuration
device_type: "dsi24" # Ignored in demo mode
lsl_stream_name: "Ignored in demo mode" # LSL stream name from DSI-Streamer

utility_frequency: 50.0 # Ignored in demo mode

output_directory: "/home/john/Downloads"
stimulus_directory: "/home/john/Dropbox/Start_Ups/nubrain/data/stimuli/text/comprehension_questions/"

# Storage bucket where to upload hdf5 file at the end of each run
storage_bucket_name: "Ignored in demo mode"
# Name of the storage object ("blob") to create
storage_blob_name: "Ignored in demo mode"
# File with credentials for uploading to storage bucket
storage_bucket_credentials: "Ignored in demo mode"

# Timing parameters:
initial_rest_duration: 3.0

stimulus_duration: 0.5
stimulus_jitter: 0.1 # Random jitter up to x seconds added to stimulus duration

isi_duration: 0.0
isi_jitter: 0.0 # Random jitter up to x seconds added to ISI

inter_block_rest_duration: 6.0
n_chars_long_word_threshold: 9 # Extend stimulus duration for long words longer than x characters.
extra_duration_per_char: 0.1 # Extra stimulus duration per character above threshold.
max_extra_stimulus_duration: 0.4 # Never prolong stimulus duration for more than x seconds (irrespective of number of characters)

# section_idx_start: 0  # Moved to `session_config.yaml` for ease of use.
stimuli_per_block: 101
stimulus_font_sizes: [56, 64, 72]
stimulus_font_min_spacing: 0.0
stimulus_font_max_spacing: 32.0

# Not needed for DSI-24, leave as null or omit
# eeg_device_address:
